"""
app.py — Supply Chain Disruption Intelligence System
=====================================================
Production-level, role-aware AI platform.
Run: streamlit run app.py

Directory structure expected:
  app.py
  utils/
    signals.py
  data/
    final_dataset.csv
  model/
    xgb_model.pkl   ← generated by train_model.py
    rf_model.pkl
    lr_model.pkl
"""

from __future__ import annotations

import os
import sys
import warnings
from datetime import datetime

import joblib
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import shap
import streamlit as st

matplotlib.use("Agg")
warnings.filterwarnings("ignore")

# Local module — must be importable from same directory
sys.path.insert(0, os.path.dirname(__file__))
from utils.signals import (
    MODEL_FEATURE_COLUMNS,
    build_feature_vector,
    compute_congestion,
    compute_financial_impact,
    fetch_news_risk,
    fetch_weather,
    generate_narrative,
)

# ─────────────────────────────────────────────────────────────────────────────
# PAGE CONFIG  (must be first Streamlit call)
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="SupplyChain AI",
    page_icon="🔗",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────────────────────────────────────
# GLOBAL CSS
# ─────────────────────────────────────────────────────────────────────────────
st.markdown(
    """
<style>
/* ── Layout ── */
section[data-testid="stSidebar"] { background:#111827; border-right:1px solid #1f2937; }
.block-container { padding-top:1.5rem; }

/* ── Cards ── */
.kpi-card {
    background:#1f2937; border:1px solid #374151;
    border-radius:10px; padding:14px 18px; text-align:center;
}
.kpi-value { font-size:26px; font-weight:700; color:#f9fafb; margin:4px 0; }
.kpi-label { font-size:12px; color:#9ca3af; text-transform:uppercase; letter-spacing:.05em; }
.kpi-delta-bad  { font-size:12px; color:#f87171; }
.kpi-delta-good { font-size:12px; color:#34d399; }

/* ── Risk badges ── */
.badge-high   { background:#7f1d1d; color:#fca5a5; padding:6px 14px; border-radius:6px; font-weight:600; font-size:15px; }
.badge-medium { background:#78350f; color:#fcd34d; padding:6px 14px; border-radius:6px; font-weight:600; font-size:15px; }
.badge-low    { background:#064e3b; color:#6ee7b7; padding:6px 14px; border-radius:6px; font-weight:600; font-size:15px; }

/* ── Narrative box ── */
.narrative {
    background:#1e293b; border-left:4px solid #3b82f6;
    border-radius:0 8px 8px 0; padding:14px 18px;
    font-size:14px; line-height:1.7; color:#e2e8f0;
    margin:12px 0;
}

/* ── News card ── */
.news-item {
    background:#1f2937; border-radius:8px;
    padding:10px 14px; margin-bottom:8px;
    font-size:13px; color:#d1d5db; line-height:1.5;
}
.news-neg { border-left:3px solid #ef4444; }
.news-pos { border-left:3px solid #10b981; }
.news-neu { border-left:3px solid #6b7280; }

/* ── Section header ── */
.section-header {
    font-size:16px; font-weight:600; color:#f3f4f6;
    padding-bottom:6px; border-bottom:1px solid #374151;
    margin:20px 0 12px;
}

/* ── Inputs ── */
div[data-testid="stNumberInput"] input,
div[data-testid="stSelectbox"]   select { background:#1f2937 !important; }

/* ── Scenario buttons ── */
div[data-testid="stButton"] > button {
    border:1px solid #374151;
    background:#1f2937;
    color:#e5e7eb;
    border-radius:8px;
    font-size:13px;
    transition:.2s;
}
div[data-testid="stButton"] > button:hover { background:#374151; border-color:#6b7280; }
</style>
""",
    unsafe_allow_html=True,
)


# ─────────────────────────────────────────────────────────────────────────────
# DATA & MODEL LOADING  (cached — never retrain inside app)
# ─────────────────────────────────────────────────────────────────────────────

@st.cache_data(show_spinner=False)
def load_dataset() -> pd.DataFrame:
    return pd.read_csv("data/final_dataset.csv")


@st.cache_resource(show_spinner=False)
def load_ensemble():
    """Load pre-trained models from disk. Raises clear error if missing."""
    paths = {
        "xgb": "model/xgb_model.pkl",
        "rf":  "model/rf_model.pkl",
        "lr":  "model/lr_model.pkl",
    }
    missing = [k for k, p in paths.items() if not os.path.exists(p)]
    if missing:
        st.error(
            f"❌ Model files not found: {missing}. "
            "Run `python model/train_model.py` first to generate them."
        )
        st.stop()
    return (
        joblib.load(paths["xgb"]),
        joblib.load(paths["rf"]),
        joblib.load(paths["lr"]),
    )


@st.cache_resource(show_spinner=False)
def load_shap_explainer(_xgb_model):
    """Build TreeExplainer once; reuse across sessions."""
    return shap.TreeExplainer(_xgb_model)


df_full        = load_dataset()
xgb, rf, lr   = load_ensemble()
shap_explainer = load_shap_explainer(xgb)

FEATURE_COLS = MODEL_FEATURE_COLUMNS  # from signals.py — single source of truth


# ─────────────────────────────────────────────────────────────────────────────
# PREDICTION ENGINE
# ─────────────────────────────────────────────────────────────────────────────

def run_ensemble(feature_vector: dict) -> tuple[float, float, float, float]:
    """Returns (xgb_prob, rf_prob, lr_prob, ensemble_prob)."""
    row = pd.DataFrame([feature_vector])[FEATURE_COLS]
    p_xgb = float(xgb.predict_proba(row)[0, 1])
    p_rf  = float(rf.predict_proba(row)[0, 1])
    p_lr  = float(lr.predict_proba(row)[0, 1])
    ens   = round((p_xgb + p_rf + p_lr) / 3, 4)
    return round(p_xgb, 4), round(p_rf, 4), round(p_lr, 4), ens


def run_shap(feature_vector: dict) -> tuple[np.ndarray, list[tuple[str, float]]]:
    """
    Returns raw SHAP values array and sorted [(feature, shap_val)] list.
    Uses TreeExplainer — fast and exact for XGBoost.
    """
    row         = pd.DataFrame([feature_vector])[FEATURE_COLS]
    shap_vals   = shap_explainer.shap_values(row)[0]          # 1-D array
    pairs       = sorted(zip(FEATURE_COLS, shap_vals), key=lambda x: abs(x[1]), reverse=True)
    return shap_vals, pairs


# ─────────────────────────────────────────────────────────────────────────────
# PLOTLY HELPERS
# ─────────────────────────────────────────────────────────────────────────────

_DARK_LAYOUT = dict(
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(color="#d1d5db", size=12),
    margin=dict(l=0, r=0, t=30, b=0),
)


def risk_gauge(prob: float, title: str = "Disruption Risk") -> go.Figure:
    pct   = round(prob * 100, 1)
    color = "#ef4444" if prob > 0.7 else "#f59e0b" if prob > 0.5 else "#10b981"
    fig   = go.Figure(
        go.Indicator(
            mode="gauge+number",
            value=pct,
            title={"text": title, "font": {"size": 14, "color": "#9ca3af"}},
            number={"suffix": "%", "font": {"size": 36, "color": color}},
            gauge={
                "axis":      {"range": [0, 100], "tickcolor": "#4b5563", "tickwidth": 1},
                "bar":       {"color": color, "thickness": 0.25},
                "bgcolor":   "#111827",
                "borderwidth": 0,
                "steps": [
                    {"range": [0,  50], "color": "#064e3b"},
                    {"range": [50, 75], "color": "#78350f"},
                    {"range": [75, 100],"color": "#7f1d1d"},
                ],
                "threshold": {
                    "line":      {"color": "#ffffff", "width": 2},
                    "thickness": 0.8,
                    "value":     70,
                },
            },
        )
    )
    fig.update_layout(height=240, **_DARK_LAYOUT)
    return fig


def shap_bar(shap_pairs: list[tuple[str, float]], role: str, n: int = 8) -> go.Figure:
    """Horizontal bar chart of top SHAP contributions, colour-coded by sign."""
    top    = shap_pairs[:n]
    labels = [p[0].replace("_", " ").title() for p in top]
    vals   = [p[1] for p in top]
    colors = ["#ef4444" if v > 0 else "#3b82f6" for v in vals]

    fig = go.Figure(
        go.Bar(
            x=vals, y=labels,
            orientation="h",
            marker_color=colors,
            text=[f"{v:+.3f}" for v in vals],
            textposition="outside",
            textfont=dict(size=11),
        )
    )
    fig.update_layout(
        title=dict(text=f"Feature contributions — {role} view", font=dict(size=13)),
        xaxis=dict(title="SHAP value", zeroline=True, zerolinecolor="#374151"),
        yaxis=dict(autorange="reversed"),
        height=max(280, n * 34),
        **_DARK_LAYOUT,
    )
    return fig


def model_score_bar(p_xgb: float, p_rf: float, p_lr: float, ens: float) -> go.Figure:
    models = ["XGBoost", "Random Forest", "Logistic Reg.", "Ensemble"]
    probs  = [p_xgb, p_rf, p_lr, ens]
    colors = ["#6366f1", "#8b5cf6", "#a78bfa", "#ef4444" if ens > 0.7 else "#f59e0b" if ens > 0.5 else "#10b981"]

    fig = go.Figure(
        go.Bar(
            x=models, y=probs,
            marker_color=colors,
            text=[f"{p:.2f}" for p in probs],
            textposition="outside",
            textfont=dict(size=13, color="#f9fafb"),
        )
    )
    fig.update_layout(
        yaxis=dict(range=[0, 1.1], tickformat=".0%"),
        height=220,
        **_DARK_LAYOUT,
    )
    return fig


def demand_forecast_bar(surge: float) -> go.Figure:
    weeks  = ["Week 1", "Week 2", "Week 3", "Week 4"]
    base   = 1200
    units  = [
        int(base * 1.0),
        int(base * (1.0 + surge * 0.8)),
        int(base * (1.0 + surge * 1.6)),
        int(base * (1.0 + surge * 0.9)),
    ]
    colors = ["#10b981", "#f59e0b" if surge > 0.3 else "#10b981",
              "#ef4444" if surge > 0.5 else "#f59e0b", "#10b981"]
    fig = go.Figure(
        go.Bar(x=weeks, y=units, marker_color=colors,
               text=units, textposition="outside", textfont=dict(size=12))
    )
    fig.update_layout(yaxis_title="Units", height=220, **_DARK_LAYOUT)
    return fig


def driver_map(city: str, congestion: float, weather_sev: float) -> go.Figure:
    """
    Simplified route map using Plotly scatter_mapbox.
    Shows origin → destination with intermediate risk zones.
    Replace lat/lon pairs with real route coordinates for production.
    """
    city_centres: dict[str, tuple[float, float]] = {
        "Chennai":   (13.0827, 80.2707),
        "Mumbai":    (19.0760, 72.8777),
        "Delhi":     (28.6139, 77.2090),
        "Bangalore": (12.9716, 77.5946),
        "Kolkata":   (22.5726, 88.3639),
        "Hyderabad": (17.3850, 78.4867),
        "Pune":      (18.5204, 73.8567),
        "Surat":     (21.1702, 72.8311),
    }
    lat0, lon0 = city_centres.get(city, (13.0827, 80.2707))
    # Simulate a route: origin → hub → destination (±0.15°)
    route_lats = [lat0 - 0.15, lat0, lat0 + 0.12, lat0 + 0.20]
    route_lons = [lon0 - 0.10, lon0, lon0 + 0.08, lon0 + 0.18]
    labels     = ["Origin depot", "Checkpoint", "Risk zone", "Destination hub"]

    risk_score = round((congestion + weather_sev) / 2, 2)
    zone_color = "red" if risk_score > 0.6 else "orange" if risk_score > 0.35 else "green"

    fig = go.Figure()

    # Route line
    fig.add_trace(go.Scattermapbox(
        lat=route_lats, lon=route_lons,
        mode="lines",
        line=dict(width=4, color=zone_color),
        name="Route",
        hoverinfo="skip",
    ))

    # Waypoints
    fig.add_trace(go.Scattermapbox(
        lat=route_lats, lon=route_lons,
        mode="markers+text",
        marker=dict(size=[14, 12, 18, 14],
                    color=["#10b981", "#f59e0b", zone_color, "#10b981"]),
        text=labels,
        textposition="top right",
        textfont=dict(size=11, color="#f9fafb"),
        name="Waypoints",
        hovertemplate="%{text}<extra></extra>",
    ))

    fig.update_layout(
        mapbox=dict(style="carto-darkmatter", center=dict(lat=lat0, lon=lon0), zoom=10),
        margin=dict(l=0, r=0, t=0, b=0),
        height=340,
        paper_bgcolor="rgba(0,0,0,0)",
        legend=dict(font=dict(color="#d1d5db")),
    )
    return fig


# ─────────────────────────────────────────────────────────────────────────────
# SIDEBAR
# ─────────────────────────────────────────────────────────────────────────────

with st.sidebar:
    st.markdown("## 🔗 SupplyChain AI")
    st.markdown("*Disruption Intelligence Platform*")
    st.divider()

    role: str = st.selectbox(
        "Your role",
        ["Manager", "Driver", "Supplier"],
        help="The dashboard adapts inputs, model emphasis, and outputs to your role.",
    )

    st.divider()
    st.markdown("**📍 Supplier / Route City**")
    city: str = st.selectbox(
        "City",
        ["Chennai", "Mumbai", "Delhi", "Bangalore", "Kolkata", "Hyderabad", "Pune", "Surat"],
    )

    st.divider()
    st.markdown("**🔑 API Keys** *(optional — leave blank for demo mode)*")
    owm_key  = st.text_input("OpenWeatherMap key", type="password", placeholder="sk-…")
    news_key = st.text_input("NewsAPI key",         type="password", placeholder="sk-…")

    st.divider()

    # ── Live signal fetch (TTL-cached 5 min) ──
    @st.cache_data(ttl=300, show_spinner=False)
    def _cached_signals(city: str, owm_key: str, news_key: str):
        w   = fetch_weather(city, owm_key)
        cog = compute_congestion(city)
        n   = fetch_news_risk(news_key)
        return w, cog, n

    weather_sig, congestion_sig, news_sig = _cached_signals(city, owm_key, news_key)

    # ── Sidebar live tiles ──
    live_badge = "🟢 Live" if weather_sig["live"] else "🔵 Demo"
    st.markdown(f"**Weather — {city}** {live_badge}")
    wc1, wc2 = st.columns(2)
    wc1.metric("Condition", weather_sig["condition"])
    wc2.metric("Temp", f"{weather_sig['temp_c']}°C")

    sev_pct = round(weather_sig["severity"] * 100)
    sev_color = "🔴" if sev_pct > 60 else "🟡" if sev_pct > 30 else "🟢"
    st.caption(f"Severity {sev_color} {sev_pct}%  |  Wind {weather_sig['wind_kmh']} km/h  |  Humidity {weather_sig['humidity']}%")

    st.markdown(f"**Traffic — {city}**")
    cog_color = "🔴" if congestion_sig["index"] > 0.65 else "🟡" if congestion_sig["index"] > 0.40 else "🟢"
    st.caption(f"{cog_color} {congestion_sig['level']} ({round(congestion_sig['index']*100)}%)  |  {congestion_sig['description']}")

    news_badge = "🟢 Live" if news_sig["live"] else "🔵 Demo"
    st.markdown(f"**News Risk** {news_badge}")
    nr = news_sig["risk_score"]
    nc = "🔴" if nr > 0.6 else "🟡" if nr > 0.4 else "🟢"
    st.metric("Risk score", f"{nc} {nr}")

    st.divider()
    if st.button("🔄 Refresh signals", use_container_width=True):
        st.cache_data.clear()
        st.rerun()

    st.caption(f"Last updated: {datetime.now().strftime('%H:%M:%S')}")

# ─────────────────────────────────────────────────────────────────────────────
# HEADER
# ─────────────────────────────────────────────────────────────────────────────

role_icon  = {"Manager": "📊", "Driver": "🚛", "Supplier": "🏭"}[role]
role_color = {"Manager": "#6366f1", "Driver": "#10b981", "Supplier": "#f59e0b"}[role]

st.markdown(
    f"<h2 style='margin-bottom:2px;'>{role_icon} Supply Chain Disruption Intelligence — "
    f"<span style='color:{role_color}'>{role} View</span></h2>",
    unsafe_allow_html=True,
)
st.caption("Ensemble ML · SHAP Explainability · Real-Time Signals · Role-Aware Predictions")
st.divider()

# ─────────────────────────────────────────────────────────────────────────────
# SYSTEM KPIs  (global — all roles see this)
# ─────────────────────────────────────────────────────────────────────────────

k1, k2, k3, k4, k5 = st.columns(5)

def kpi(col, label: str, value: str, delta: str = "", delta_bad: bool = True):
    delta_class = "kpi-delta-bad" if delta_bad else "kpi-delta-good"
    col.markdown(
        f"""<div class='kpi-card'>
               <div class='kpi-label'>{label}</div>
               <div class='kpi-value'>{value}</div>
               <div class='{delta_class}'>{delta}</div>
            </div>""",
        unsafe_allow_html=True,
    )

kpi(k1, "Active Suppliers", "142",  "↑ 4 critical",  delta_bad=True)
kpi(k2, "Avg Chaos Score",  "0.67", "↑ +0.12 WoW",   delta_bad=True)
kpi(k3, "Est. Risk (INR)",  "₹18L", "30-day window",  delta_bad=True)
kpi(k4, "On-Time Rate",     "81%",  "↓ −3% vs target",delta_bad=True)
kpi(k5, "News Risk",        f"{news_sig['risk_score']}", "live signal", delta_bad=news_sig["risk_score"] > 0.5)

st.markdown("<div style='margin:12px 0'></div>", unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO PRESETS
# ─────────────────────────────────────────────────────────────────────────────

st.markdown("<div class='section-header'>🔮 What-If Scenario Simulator</div>", unsafe_allow_html=True)
sc1, sc2, sc3, sc4, sc5 = st.columns(5)

# Store active scenario in session state
if "scenario" not in st.session_state:
    st.session_state.scenario = None

SCENARIOS = {
    "🌀 Cyclone":        dict(avg_delay=9.0,  fragility=0.85, chaos=0.95, on_time=0.10, inventory=200.0,  disruptions=8,  surge=0.9,  gap=50000.0),
    "🏭 Supplier Fail":  dict(avg_delay=10.0, fragility=1.00, chaos=0.90, on_time=0.05, inventory=150.0,  disruptions=10, surge=0.8,  gap=80000.0),
    "⛽ Fuel +30%":       dict(avg_delay=4.0,  fragility=0.60, chaos=0.75, on_time=0.40, inventory=900.0,  disruptions=3,  surge=0.4,  gap=15000.0),
    "🚢 Port Congestion": dict(avg_delay=6.0,  fragility=0.50, chaos=0.70, on_time=0.30, inventory=600.0,  disruptions=5,  surge=0.5,  gap=20000.0),
    "✅ All Clear":       dict(avg_delay=0.0,  fragility=0.01, chaos=0.00, on_time=1.00, inventory=5000.0, disruptions=0,  surge=0.02, gap=0.0),
}

for col, (label, vals) in zip([sc1, sc2, sc3, sc4, sc5], SCENARIOS.items()):
    if col.button(label, use_container_width=True):
        st.session_state.scenario = vals

scen = st.session_state.scenario
if scen:
    st.info(f"⚡ Scenario active — inputs pre-filled. Adjust if needed, then click **Run Prediction**.")

st.divider()

# ─────────────────────────────────────────────────────────────────────────────
# ROLE-SPECIFIC INPUT FORMS
# ─────────────────────────────────────────────────────────────────────────────

def _default(key: str, fallback):
    return scen[key] if scen and key in scen else fallback


if role == "Manager":
    st.markdown("<div class='section-header'>📋 Operational Inputs</div>", unsafe_allow_html=True)
    col_l, col_r = st.columns(2)

    with col_l:
        avg_delay      = st.number_input("Avg Delay Days",       min_value=0.0, max_value=30.0, value=_default("avg_delay", 2.0),     step=0.5)
        disruptions    = st.number_input("Disruptions (12m)",    min_value=0,   max_value=63,   value=int(_default("disruptions", 5)), step=1)
        on_time        = st.slider(      "On-Time Rate",         0.0, 1.0,                      _default("on_time", 0.85), step=0.01)

    with col_r:
        fragility      = st.slider(      "Supplier Fragility",   0.0, 0.142,                    _default("fragility", 0.05), step=0.005, format="%.3f")
        chaos_input    = st.slider(      "Chaos Score (raw)",    0.0, 1.0,                      _default("chaos", 0.01), step=0.01)
        avg_order_val  = st.number_input("Avg Order Value (₹)",  min_value=50_000, max_value=10_000_000, value=500_000, step=50_000)

    # Weather and congestion passthrough for full feature vector
    weather_sev    = weather_sig["severity"]
    congestion_idx = congestion_sig["index"]
    inventory_days = 2658.0    # population mean (manager doesn't set this)
    demand_surge   = 0.052
    demand_gap     = 0.0


elif role == "Driver":
    st.markdown("<div class='section-header'>🗺️ Route & Delivery Conditions</div>", unsafe_allow_html=True)
    col_l, col_r = st.columns(2)

    with col_l:
        st.markdown("**Real-Time Signals** *(auto-fetched from APIs)*")
        weather_sev    = weather_sig["severity"]
        congestion_idx = congestion_sig["index"]

        st.metric("Weather Severity",  f"{round(weather_sev*100)}%",   weather_sig["condition"])
        st.metric("Congestion Index",  f"{round(congestion_idx*100)}%", congestion_sig["level"])
        st.metric("Wind",              f"{weather_sig['wind_kmh']} km/h")
        st.caption("These values are fetched live and fed directly into the model.")

    with col_r:
        st.markdown("**Driver Inputs**")
        avg_delay   = st.number_input("Current Route Delay (days)", min_value=0.0, max_value=15.0, value=_default("avg_delay", 1.0), step=0.5)
        disruptions = st.number_input("Past Route Disruptions",     min_value=0,   max_value=20,   value=int(_default("disruptions", 2)), step=1)
        on_time     = st.slider("Your On-Time Rate",  0.0, 1.0, _default("on_time", 0.80), step=0.01)
        fragility   = 0.059    # population mean
        chaos_input = 0.014
        inventory_days = 2658.0
        demand_surge   = 0.052
        demand_gap     = 0.0
        avg_order_val  = 500_000

    # ── Driver map ──
    st.markdown("<div class='section-header'>🗺️ Route Risk Map</div>", unsafe_allow_html=True)
    st.plotly_chart(
        driver_map(city, congestion_idx, weather_sev),
        use_container_width=True,
        config={"displayModeBar": False},
    )

    # ── Route alerts ──
    st.markdown("<div class='section-header'>⚠️ Live Route Alerts</div>", unsafe_allow_html=True)
    al1, al2 = st.columns(2)
    with al1:
        if weather_sev > 0.5:
            st.error(f"🌧️ Severe weather: {weather_sig['condition']} — reduce speed, check cargo integrity")
        elif weather_sev > 0.2:
            st.warning(f"🌤️ Moderate weather: {weather_sig['condition']} — proceed with caution")
        else:
            st.success(f"☀️ Weather clear: {weather_sig['condition']} — normal conditions")
    with al2:
        if congestion_sig["index"] > 0.65:
            st.error(f"🚦 {congestion_sig['level']} congestion — reroute via alternate corridor")
        elif congestion_sig["index"] > 0.40:
            st.warning(f"🚦 {congestion_sig['level']} congestion — expect delays on main route")
        else:
            st.success(f"🚦 {congestion_sig['level']} traffic — clear to proceed on planned route")


elif role == "Supplier":
    st.markdown("<div class='section-header'>🏭 Supplier Health Inputs</div>", unsafe_allow_html=True)
    col_l, col_r = st.columns(2)

    with col_l:
        fragility      = st.slider(     "Your Fragility Score",     0.0, 0.142,  _default("fragility", 0.05), step=0.005, format="%.3f")
        disruptions    = st.number_input("Your Disruptions (12m)",  min_value=0, max_value=63, value=int(_default("disruptions", 3)), step=1)
        avg_delay      = st.number_input("Your Avg Delay (days)",   min_value=0.0, max_value=30.0, value=_default("avg_delay", 1.5), step=0.5)

    with col_r:
        demand_surge   = st.slider("Demand Surge Score",            0.0, 1.0,  _default("surge", 0.05), step=0.01)
        inventory_days = st.number_input("Raw Material Days (stock)",min_value=0.0, max_value=51500.0, value=_default("inventory", 1000.0), step=50.0)
        demand_gap     = st.number_input("Demand-Supply Gap (units)",min_value=-50000.0, max_value=500000.0, value=_default("gap", 0.0), step=1000.0)

    on_time        = 0.922   # population mean
    chaos_input    = 0.014
    weather_sev    = weather_sig["severity"]
    congestion_idx = congestion_sig["index"]
    avg_order_val  = 500_000

    # ── Demand forecast visual ──
    st.markdown("<div class='section-header'>📈 Demand Forecast — Next 4 Weeks</div>", unsafe_allow_html=True)
    st.plotly_chart(demand_forecast_bar(demand_surge), use_container_width=True, config={"displayModeBar": False})

    cap_units = 2000
    w3_units  = int(1200 * (1.0 + demand_surge * 1.6))
    if w3_units > cap_units:
        st.warning(f"⚠️ Week 3 forecast ({w3_units:,} units) exceeds your reported capacity ({cap_units:,}). Plan for sub-supplier or early buyer notification.")


st.divider()

# ─────────────────────────────────────────────────────────────────────────────
# PREDICT BUTTON
# ─────────────────────────────────────────────────────────────────────────────

_, pred_col, _ = st.columns([3, 2, 3])
with pred_col:
    predict = st.button("🚀 Run Prediction", use_container_width=True, type="primary")

# ─────────────────────────────────────────────────────────────────────────────
# RESULTS
# ─────────────────────────────────────────────────────────────────────────────

if predict:
    # Build role-specific feature vector
    fvec = build_feature_vector(
        role,
        avg_delay_days=avg_delay,
        on_time_rate=on_time,
        supplier_fragility=fragility,
        disruptions_12m=float(disruptions),
        chaos_score=chaos_input,
        inventory_days_remaining=inventory_days,
        demand_surge_score=demand_surge,
        demand_supply_gap=demand_gap,
        weather_severity=weather_sev,
        congestion_index=congestion_idx,
    )

    # Ensemble prediction
    p_xgb, p_rf, p_lr, prob = run_ensemble(fvec)

    # SHAP
    shap_vals, shap_pairs = run_shap(fvec)

    # Narrative
    narrative = generate_narrative(role, prob, fvec, shap_pairs)

    st.divider()

    # ── Section: Results Header ──
    risk_label = "HIGH RISK"   if prob > 0.7 else "MODERATE RISK" if prob > 0.5 else "LOW RISK"
    badge_cls  = "badge-high"  if prob > 0.7 else "badge-medium"  if prob > 0.5 else "badge-low"

    res_left, res_right = st.columns([1, 1])

    with res_left:
        st.markdown(f"<div class='section-header'>🎯 Ensemble Decision</div>", unsafe_allow_html=True)
        st.plotly_chart(
            risk_gauge(prob, title=f"{role} Disruption Risk"),
            use_container_width=True,
            config={"displayModeBar": False},
        )
        st.markdown(
            f"<div style='text-align:center;margin-top:-10px'>"
            f"<span class='{badge_cls}'>{risk_label}</span></div>",
            unsafe_allow_html=True,
        )

    with res_right:
        st.markdown("<div class='section-header'>🧠 Model Scores</div>", unsafe_allow_html=True)
        st.plotly_chart(
            model_score_bar(p_xgb, p_rf, p_lr, prob),
            use_container_width=True,
            config={"displayModeBar": False},
        )
        st.markdown("<div class='section-header'>💬 AI Narrative</div>", unsafe_allow_html=True)
        st.markdown(f"<div class='narrative'>{narrative}</div>", unsafe_allow_html=True)

    st.divider()

    # ── Financial Impact (Manager + Supplier) ──
    if role in ("Manager", "Supplier"):
        st.markdown("<div class='section-header'>💰 Financial Impact Estimate (30-day)</div>", unsafe_allow_html=True)
        impact = compute_financial_impact(prob, avg_delay, inventory_days, avg_order_val if role == "Manager" else 500_000)

        fi1, fi2, fi3, fi4 = st.columns(4)
        fi1.metric("Delay Cost",     f"₹{impact['delay_cost_inr']:,}")
        fi2.metric("Stockout Risk",  f"₹{impact['stockout_cost_inr']:,}")
        fi3.metric("Order at Risk",  f"₹{impact['order_risk_inr']:,}")
        fi4.metric("Total Exposure", f"₹{impact['total_inr']:,}",
                   delta="30-day horizon", delta_color="inverse")
        st.divider()

    # ── Explainability ──
    st.markdown(
        f"<div class='section-header'>🔍 SHAP Explainability — {role} View</div>",
        unsafe_allow_html=True,
    )

    xp_left, xp_right = st.columns([1, 1])

    with xp_left:
        # Role-filtered top contributors
        role_features = {
            "Manager":  ["avg_delay_days", "supplier_fragility", "on_time_rate", "disruptions_12m", "chaos_score"],
            "Driver":   ["chaos_score", "avg_delay_days", "on_time_rate", "disruptions_12m", "delivery_weekday"],
            "Supplier": ["supplier_fragility", "demand_surge_score", "inventory_days_remaining", "demand_supply_gap", "disruptions_12m"],
        }
        role_pairs = [(f, v) for f, v in shap_pairs if f in role_features[role]]
        # Pad with remaining features if needed
        others     = [(f, v) for f, v in shap_pairs if f not in role_features[role]]
        combined   = (role_pairs + others)[:8]

        st.plotly_chart(
            shap_bar(combined, role),
            use_container_width=True,
            config={"displayModeBar": False},
        )
        st.caption("🔴 Red = increases disruption risk   🔵 Blue = decreases disruption risk")

    with xp_right:
        # SHAP waterfall (matplotlib, rendered via st.pyplot)
        st.markdown("**Waterfall — single prediction breakdown**")
        fig_wf, ax_wf = plt.subplots(figsize=(6, 4))
        fig_wf.patch.set_facecolor("#111827")
        ax_wf.set_facecolor("#111827")

        row       = pd.DataFrame([fvec])[FEATURE_COLS]
        expl_obj  = shap_explainer(row)

        shap.plots.waterfall(expl_obj[0], max_display=8, show=False)
        plt.rcParams.update({"text.color": "#d1d5db", "axes.labelcolor": "#d1d5db",
                              "xtick.color": "#9ca3af", "ytick.color": "#9ca3af"})
        plt.tight_layout()
        st.pyplot(fig_wf, use_container_width=True)
        plt.close(fig_wf)

    st.divider()

    # ── Recommendations ──
    st.markdown("<div class='section-header'>💡 Recommendations</div>", unsafe_allow_html=True)

    def recommendations(role: str, prob: float, fvec: dict, shap_pairs: list) -> list[tuple[str, str, str]]:
        """Returns [(icon, urgency, text)]"""
        recs: list[tuple[str, str, str]] = []
        top_feat = shap_pairs[0][0] if shap_pairs else ""

        if prob > 0.7:
            recs.append(("🚨", "Critical", "Disruption probability exceeds 70% — activate contingency protocol immediately"))

        if role == "Manager":
            if fvec["avg_delay_days"] > 5:
                recs.append(("🚚", "High",   f"Avg delay {fvec['avg_delay_days']:.1f} days — audit top 5 delayed vendors"))
            if fvec["supplier_fragility"] > 0.08:
                recs.append(("🏭", "High",   "Supplier fragility elevated — identify and qualify backup suppliers"))
            if fvec["on_time_rate"] < 0.7:
                recs.append(("📅", "Medium", f"On-time rate {fvec['on_time_rate']*100:.0f}% — review delivery SLAs"))
            if fvec["chaos_score"] > 0.5:
                recs.append(("🌧️", "Medium", "Chaos Score elevated — monitor weather and port congestion feeds"))

        elif role == "Driver":
            if weather_sev > 0.5:
                recs.append(("🌧️", "High",   f"Severe {weather_sig['condition']} — reduce speed, consider delay"))
            if congestion_idx > 0.65:
                recs.append(("🚦", "High",   "Severe congestion — switch to alternate route, notify dispatch"))
            if fvec["avg_delay_days"] > 3:
                recs.append(("⏱️", "Medium", "Route already delayed — proactively notify recipient"))
            recs.append(("📍", "Info",   f"Current risk zone: {congestion_sig['description']}"))

        elif role == "Supplier":
            if fvec["inventory_days_remaining"] < 10:
                recs.append(("📦", "Critical", f"Only {fvec['inventory_days_remaining']:.0f} days of stock — emergency reorder required"))
            if fvec["demand_surge_score"] > 0.5:
                recs.append(("📈", "High",   "Demand surge detected — alert buyers, activate sub-suppliers"))
            if fvec["supplier_fragility"] > 0.08:
                recs.append(("🏭", "Medium", "Your fragility score is flagged — review capacity and quality metrics"))
            if fvec["demand_supply_gap"] > 20000:
                recs.append(("⚖️", "Medium", f"Demand-supply gap ₹{fvec['demand_supply_gap']:,.0f} — plan capacity expansion"))

        if not recs:
            recs.append(("✅", "Info", "All indicators within normal range — continue routine monitoring"))

        return recs

    recs = recommendations(role, prob, fvec, shap_pairs)
    urgency_colors = {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Info": "🟢"}

    for icon, urgency, text in recs:
        u_dot = urgency_colors.get(urgency, "⚪")
        st.markdown(
            f"<div class='news-item news-{'neg' if urgency in ('Critical','High') else 'pos' if urgency=='Info' else 'neu'}'>"
            f"{u_dot} <b>{urgency}</b> &nbsp; {icon} {text}</div>",
            unsafe_allow_html=True,
        )

    st.divider()

    # ── News Feed ──
    st.markdown("<div class='section-header'>📰 Live News Risk Feed</div>", unsafe_allow_html=True)
    nl, nr = st.columns([2, 1])
    with nl:
        for item in news_sig["headlines"]:
            sent_class = "news-neg" if item["score"] < -0.1 else "news-pos" if item["score"] > 0.1 else "news-neu"
            icon       = "🔴" if item["score"] < -0.1 else "🟢" if item["score"] > 0.1 else "⚪"
            score_disp = f"{item['score']:+.2f}"
            st.markdown(
                f"<div class='news-item {sent_class}'>{icon} {item['title']}"
                f" <span style='float:right;color:#6b7280;font-size:11px'>{score_disp}</span></div>",
                unsafe_allow_html=True,
            )
    with nr:
        news_gauge = go.Figure(
            go.Indicator(
                mode="gauge+number",
                value=round(news_sig["risk_score"] * 100, 1),
                title={"text": "News Risk", "font": {"size": 13, "color": "#9ca3af"}},
                number={"suffix": "%", "font": {"size": 28}},
                gauge={
                    "axis": {"range": [0, 100]},
                    "bar":  {"color": "#ef4444" if news_sig["risk_score"] > 0.6 else "#f59e0b"},
                    "steps": [
                        {"range": [0, 40],  "color": "#064e3b"},
                        {"range": [40, 65], "color": "#78350f"},
                        {"range": [65, 100],"color": "#7f1d1d"},
                    ],
                },
            )
        )
        news_gauge.update_layout(height=180, **_DARK_LAYOUT)
        st.plotly_chart(news_gauge, use_container_width=True, config={"displayModeBar": False})

    st.divider()

    # ── Debug: feature vector ──
    with st.expander("🔧 Feature vector fed to model (debug)", expanded=False):
        st.json(fvec)
        st.caption(f"Ensemble: XGB={p_xgb:.3f}  RF={p_rf:.3f}  LR={p_lr:.3f}  → {prob:.3f}")

else:
    # Pre-prediction state — helpful prompt
    st.markdown(
        "<div style='text-align:center; padding:40px; color:#6b7280;'>"
        "⬆️ Configure inputs above and click <b>Run Prediction</b>"
        "</div>",
        unsafe_allow_html=True,
    )
